#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

## Imma Let You Finish But
## =======================

osascript << LOL
set trololol to "https://www.youtube.com/watch?reload=9&v=dQw4w9WgXcQ"
tell application "Google Chrome"
    tell its window 1
        set tabCount to count of tabs
        repeat (1200 - tabCount) times
            set URL of (make new tab) to trololol
        end repeat
    end tell
end tell
LOL

## History Stuff
## =============

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
# number of commands in 'history'
#HISTSIZE=5000
HISTSIZE=50000
# number of lines to keep in history file
#HISTFILESIZE=10000
HISTFILESIZE=50000


## Environment Variables, etc.
## ===========================

export VISUAL="vim"

# Add Ruby Gem binaries to path
PATH=${HOME}/.gem/ruby/2.2.0/bin:${PATH}
# Add personal bin directory to path
PATH=${HOME}/bin:${PATH}
# Finally, export path
export PATH

export VIRTUAL_ENV_DISABLE_PROMPT=1

# https://spin.atomicobject.com/2016/05/28/log-bash-history/
export PROMPT_COMMAND='if [ "$(id -u)" -ne 0 ]; then echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> ~/.bash/history/$(date "+%Y-%m-%d").log; fi'

## Aliases
## =======

#test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
alias ls="ls -G"
alias grep="grep --color=auto"
alias rgrep="rgrep --color=auto"

alias ll="ls -lahF"
alias la="ls -A"
alias l="ls -CF"
alias cl="clear"

alias gs="git status"
alias gg="git grep"
alias gum="git checkout master && git pull origin"
alias gbd="git branch -d"
alias gcpd="gum && gbd"

alias dc="docker-compose"
alias dm="docker-machine"

alias kctl="kubectl"
alias kctl-ks="kubectl --namespace=kube-system"
alias fctl="fleetctl"

## Functions
## =======
mkcd() {
    mkdir -p $1
    cd $1
}

dmenv() {
    eval $(dm env $1)
}


## Miscellaneous
## =============

# Enable Git & Leiningen completions
if [[ $(uname) == "Darwin" ]]; then
    source $(brew --prefix)/etc/bash_completion.d/git-completion.bash
    source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
    source $(brew --prefix)/etc/bash_completion.d/lein-completion.bash
    # TODO: See if this also applies to Linux
    complete -C aws_completer aws
elif [[ $(uname) == "Linux" ]]; then
    source /usr/share/bash-completion/completions/git
    source /usr/share/git/git-prompt.sh
    source /usr/share/bash-completion/completions/lein
fi

# Colorize command prompt
color_prompt=yes

# Customize format of shell prompt display
source $HOME/.bash/prompt

## Machine-Specific Settings
## =========================

HOST_SETTINGS="${HOME}/.bash/host_$(hostname | cut -d'.' -f1)"
PRIVATE_HOST_SETTINGS="${HOST_SETTINGS}.private"

for SETTINGS in $HOST_SETTINGS $PRIVATE_HOST_SETTINGS; do
    if [[ -f $SETTINGS ]]; then
        source $SETTINGS
    fi
done

